language: cpp
os:
 - linux
 - osx

# When updating be sure to add a section
# to the matrix to cover the distro
dist: bionic

compiler:
    - gcc
    - clang

jobs:
    include:
        - os: linux
          dist: xenial
          compiler: gcc
          name: "Ubuntu 16.04 LTS - GCC"
        - os: linux
          dist: xenial
          compiler: clang
          name: "Ubuntu 16.04 LTS - Clang"
        - os: osx
          osx_image: xcode11.3
    allow_failures:
        - os: osx
    fast_finish: true

addons:
  apt:
    packages:
      - python-dev
      - libgl1-mesa-glx
      - freeglut3-dev
      - libopenal-dev
      - libsdl-gfx1.2-dev
      - libvorbis-dev
      - libjpeg-dev
      - libpng-dev
      - libgtk2.0-dev
      - libboost-python-dev
  homebrew:
     update: true
     packages:
      - mesa
      - openal-soft
      - sdl
      - libvorbis
      - jpeg
      - libpng
      - gtk+
      - gtkglext
      - boost-python

script:
  - ./sh/vsbuild.sh

# CI/CD hookups
# See https://docs.travis-ci.com/user/deployment/releases/
# for what to do for `before_deploy` and `deploy` sections
before_deploy:
#  - pull the submodule here
  - ./sh/vspackage.sh
  - pwd
  - ls
  - ls packages
#  - export TRAVIS_TAG="composite tag name here"
#  - git tag ${TRAVIS_TAG}
deploy:
#    # GitHub Releases
    provider: releases
    token: $GITHUB_TOKEN
    file:
       # Upload files in the `packages` directory
       - ./packages/*
#    # Ensure the build doesn't get cleaned up so the files are avialable
#    # for the release build
    skip_cleanup: true
#    # release is a draft so it can be edited, updated, etc.
#    # Not needed as we'll do that manually when we'll begin the release.
#    draft: true
#    prerelease: true
#    # GitHub Releases requires a tag; this guarnatees a tag is set
    on:
        tags: true
        repo: vegastrike/Vega-Strike-Engine-Source
        # We're compiling the same thing twice, no need to deploy it twice.
        condition: "$CC != gcc"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1361517953461007f39a  # community room
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
